###########
# site.url, site.title

title: 'Gabriel a Jekyll Bootstrap Theme'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)

path: /mrmccormack.github.io
url: 'mrmccormack/mrmccormack.github.io'


########
# more settings

# https://help.github.com/articles/configuring-jekyll/
# 
# Defaults you can change

# The following defaults are set by GitHub, which you are free to override in your _config.yml file:

 # github: [metadata]
 # kramdown:
 #   input: GFM
 #   hard_wrap: false
 # gems:
 #   - jekyll-coffeescript
 #   - jekyll-paginate


# markdown: kramdown

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge


kramdown:
  input: GFM




sass:
  sass_dir: css
  style:    expanded


# Social links for footer
twitter_username:     r3bl_
github_username:      aleksandar-todorovic
linkedin_username:    aleksandartodorovic
google_plus_username: AleksandarTodorovićr3bl
facebook_username:    aleksandar.todorovic.r3bl
dribbble_username:    dribble


exclude:
- README.md

# https://help.github.com/articles/sitemaps-for-github-pages/
# https://help.github.com/articles/search-engine-optimization-for-github-pages/
# https://github.com/jekyll/jekyll-seo-tag#usage
# https://help.github.com/articles/emoji-on-github-pages/
# https://github.com/jekyll/jemoji
# http://www.webpagefx.com/tools/emoji-cheat-sheet/

# Sitemap note
# - it is not in repository, but is created
# - http://mrmccormack.me/sitemap.xml
# https://github.com/kinnetica/jekyll-plugins

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji  
  - jekyll-feed  

safe: true
lsi: false

