###########
# site.url, site.title

title: 'Gabriel a Jekyll Bootstrap Theme'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)

path: /mrmccormack.github.io
url: 'mrmccormack/mrmccormack.github.io'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


syntax-highlighting:
  enabled : true
  css: syntax.css

safe: true
lsi: false

